### ISSUE TITLE
thread 'main' panicked at 'no private key found'

### ISSUE THREAD

**Issue by ctermiii** [lazytiger/trojan-rs#1]
i run it at my vps as
 ./trojan -a 0.0.0.0 -p test  server --cert  trojan.crt --key trojan.key -r 127.0.0.1:8080
 and got error message:
[2020-03-18 08:35:34.580767][src/main.rs:26][WARN]trojan started in server mode
thread 'main' panicked at 'no private key found', src/server/mod.rs:40:17

and  the cert and key file are generated by acme script , it worked fine in v2ray .

how can i fix it?

**Comment by lazytiger** [comment]
pkcs8 and rsa private keys in pem format supported for now, could check your private key format?
check this for format converting

https://stackoverflow.com/questions/991758/how-to-get-pem-file-from-key-and-crt-files

**Comment by ctermiii** [comment]
got it ,i am checking now.

**Comment by ctermiii** [comment]
i reissue the ssl certificate files; it works fine now .
thanks.
