### ISSUE TITLE
Local proxy problem.

### ISSUE THREAD

**Issue by UG40A** [lazytiger/trojan-rs#10]
Hello! 
I am faced with a difficult task: I need start client and server on same device to spoof SNI host locally. 
(If you know a more concise method of spoofing, please tell me. I need only this.)
I have root, busybox and full shell access and etc.
How should I set up the firewall rules? I tried many ways to do this, but I can't connect correctly.
I really need for your help, please. Thanks for your work!

**Comment by UG40A** [comment]
This needs to be done on Android.*
I have already compiled a working binary.
Thanks!

**Comment by lazytiger** [comment]
I am not sure if I can help. Could you give more details, like what you have done, and what's wrong?

**Comment by UG40A** [comment]
I'm getting a loop or 'connection refused' when trying to connect. I think, that the problem is in forwarding traffic, because server and client are on the same device. I tried to run the server on 127.0.0.1 and 0.0.0.0, but I understand that this is not correct in my case ... I also created a second isolated profile: in this case, I can connect, but I cannot correctly redirect/tether traffic after.
 This is a common problem for all proxies in this case and I don't know how to properly configure routing or fix it differently...
 Thanks.

**Comment by lazytiger** [comment]
Which stage did 'connection refused' happen? Did trojan client get data? Or did trojan server get data?
And if it's ok, could you share your iptable config?

**Comment by UG40A** [comment]
1. When I am trying to connect. 
2,3. No and No...
4. My iptables config is empty now, but I tried to forward the trojan traffic with prerouting. 
Thanks.

**Comment by lazytiger** [comment]
Well, if iptables config is empty, I am sure you will get connection refused problem, because trojan does not work now. Please try the iptables config in README.

**Comment by lazytiger** [comment]
This issue is not directly related to the projet, I am closing it now.
