### ISSUE TITLE
后续能否支持GRPC协议

### ISSUE THREAD

**Issue by qiuzi** [lazytiger/trojan-rs#11]
看到Xray-core有对延迟优化使用的是GRPC，后续trojan是否考虑兼容Xray的GRPC

**Comment by lazytiger** [comment]
目前还不确定，我对GRPC为什么能优化延迟不是很了解，需要去调研一下

**Comment by lazytiger** [comment]
暂时应该不会支持gRPC，目前trojan-rs的延时主要是因为tcp协议和https的连接造成的，gRPC并不能解决这些问题。反过来如果不使用https，又有被gfw识别的风险，因此暂时不会考虑这个特性。

**Comment by qiuzi** [comment]
GFW不会去解码干扰，流量一大什么加密都白费。grpc是借助cf隐藏IP作为主要跳板

**Comment by lazytiger** [comment]
目前不打算做这个支持，问题我先关闭了
