### ISSUE TITLE
Build error by cargo 1.72.0@Ubuntu 20.04.6 LTS

### ISSUE THREAD

**Issue by shinemymoon** [lazytiger/trojan-rs#15]
warning: unused imports: `SocketAddr`, `UdpSocket`
 --> src/bin/dns.rs:2:11
  |
2 |     net::{SocketAddr, UdpSocket},
  |           ^^^^^^^^^^  ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `Runtime`
 --> src/bin/dns.rs:7:31
  |
7 | use tokio::runtime::{Builder, Runtime};
  |                               ^^^^^^^

warning: function `test` is never used
  --> src/bin/dns.rs:11:4
   |
11 | fn test() {
   |    ^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `trojan` (bin "dns") generated 3 warnings (run `cargo fix --bin "dns"` to apply 2 suggestions)
error: linking with `cc` failed: exit status: 1

**Comment by lazytiger** [comment]
I don't see any errors but warnings. I guess you are missing libipset in your system.

**Comment by shinemymoon** [comment]
yeah, you are right; but after "sudo apt install ipset", it still raised the same error

**Comment by lazytiger** [comment]
sudo apt-get install libipset-dev -y

**Comment by shinemymoon** [comment]
It works, thx

**Comment by lazytiger** [comment]
close
