### ISSUE TITLE
为什么只有root账户能使用？

### ISSUE THREAD

**Issue by ghost** [lazytiger/trojan-rs#2]
![捕获](https://user-images.githubusercontent.com/36000034/85914766-c9866780-b873-11ea-83ae-501dd1bd85e3.PNG)
不用root用户报上面的错误。

客户端用trojan-rs，服务端用trojan-gfw无法使用，下图是日志
![捕获2](https://user-images.githubusercontent.com/36000034/85914905-6dbcde00-b875-11ea-93e8-cc742958d314.PNG)

curl: (7) Unable to receive initial SOCKS5 response.

**Comment by lazytiger** [comment]
1.txproxy需要root权限
2.client并不是socks5代理

**Comment by Bond171** [comment]
谢谢解答，以后会支持socks吗？

**Comment by ghost** [comment]
> 1.txproxy需要root权限
> 2.client并不是socks5代理

谢谢解答，以后会支持socks吗？

**Comment by lazytiger** [comment]
可能不会支持了，原版就有这功能了已经

**Comment by ghost** [comment]
> 可能不会支持了，原版就有这功能了已经

好的我懂了，谢谢！

**Comment by junknet** [comment]
这个原因好像是因为那个特殊的透明代理套接字，需要root权限才能监听
