### ISSUE TITLE
我能指定远程端口吗

### ISSUE THREAD

**Issue by junknet** [lazytiger/trojan-rs#4]
![qwe](https://user-images.githubusercontent.com/55597646/88962550-2b097e00-d2d9-11ea-89a3-c6436101842e.png)

proxy模式端口写死443,
我觉得proxy 模式下应该有个 remote port 参数...

**Comment by lazytiger** [comment]
这个不准备支持，trojan的核心思想是把自己伪装成https，这样就无法被识别，非标准端口无意义，有需求可以自己fork了改吧

**Comment by lazytiger** [comment]
可以指定端口，文档我已经修改了一下，address是ip:port的形式。如果是当梯子用，不建议使用除443外的非标准端口，还是有被发现的风险。

//proxy模式目前已经支持指定端口
