### ISSUE TITLE
有openwrt编译make文件吗？

### ISSUE THREAD

**Issue by qiuzi** [lazytiger/trojan-rs#5]
希望参与测试

**Comment by lazytiger** [comment]
https://suikastar.com/posts/56623/
rust支持交叉编译，参考上面文章试试

**Comment by qiuzi** [comment]
不理想
   Compiling cfg-if v0.1.10
   Compiling lazy_static v1.4.0
   Compiling slab v0.4.2
   Compiling getrandom v0.1.14
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error: aborting due to previous error

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: could not compile `lazy_static`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-musl` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `slab`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by lazytiger** [comment]
你上面这个报错的意思是你缺少x86_64-unknown-linux-musl目标，rustup target add x86_64-unknown-linux-musl 试一下
OpenWRT我不是很懂，google了一下，`For OpenWRT devices, i.e. targets mips-unknown-linux-uclibc (15.05 and older) and mips-unknown-linux-musl (post 15.05), use the OpenWRT SDK`，根据https://github.com/japaric/rust-cross

**Comment by lazytiger** [comment]
试了一下，目前应该没办法编译出来mips版本，ring组件就不支持mips，我看了一下17年就有人提了，到现在还没解决，这个问题我先关闭了

**Comment by qiuzi** [comment]
我用的是x86-64的cpu
