### ISSUE TITLE
【鸡生蛋、蛋生鸡问题】能否把服务器的连接ip、域名分开成两个设置？

### ISSUE THREAD

**Issue by cod1ingcoding** [lazytiger/trojan-rs#8]
能否把服务器的连接ip、域名分开成两个设置？
不然很容易遇到鸡生蛋、蛋生鸡问题

**Comment by cod1ingcoding** [comment]
或者加入读取 /etc/hosts文件设置也行

**Comment by lazytiger** [comment]
proxy启动的时候会根据系统默认dns来把hostname转换成ip，如果你的dns支持etc/hosts那么它就能查询出来，如果你使用的dns是dnsmasq的话，它会自动读取/etc/hosts里的值的，除非你加了no-hosts配置。另外不设置ip是因为trojan的原理来说，你需要是个正常的https服务，否则还是有可能被墙

**Comment by cattyhouse** [comment]
给个参数指定 ip 会更好.
